old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'northfire'
            password: 'northfire'
            vhost:    'northfire'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
            heartbeat: 0
    producers:
        northfire_message:
            connection: default
            exchange_options: {name: 'northfire_message', type: direct}
    consumers:
        northfire_message:
            connection: default
#            exchange_options: {name: 'northfire_message', type: direct}
            queue_options:    {name: 'northfire_message'}
            callback: 'northfire_async_member_consumer'

services:
    northfire_async_member_consumer:
        class: 'Northfire\Infrastructure\EventPublisher\MemberAsyncEventConsumer'